/* // User data model
{
    "Name": "",        <-- replace with email?(hash email)
    "Password": "",    <-- hash password
    "CreatedAt": "",     <-- auto generated by mongoose
    "games": []       <-- array of games? (game history, each game has a score, date, etc.)
    ""
    "lastLogin": ""   <-- auto generated by mongoose on login cal
}
 */

const mongoose = require("mongoose");

const Schema = mongoose.Schema;
 
const userSchema = new Schema(
  {
    userName: {
      type: String,
      required: true,
      unique: true,
    },
    /* email: {
      type: String,
      required: true,
      unique: true,
    }, */
    password: {
      type: String,
      required: true,
    },
    games: {
        gameID: {
          "Name": String,
          "Score": Number,
          //"Date": Date
        },
      }
  },
  { timestamps: true }
);

userSchema.set("toJSON", {
  virtuals: true,
  transform: (doc, ret) => {
    delete ret._id;
    delete ret.__v;
  },
});

const User = mongoose.model("User", userSchema);

module.exports = mongoose.model("User", userSchema);